"""Inject Open Graph + Twitter Card meta tags into every page so links
look rich when shared to social and messaging apps.

Material's `social` plugin can do this but needs cairosvg + image
rendering that silently no-ops in some CI environments. This hook is
simpler: it derives all tags from page + site config, no images.

og:image points at a pre-generated 1200x630 Korean or English card checked
into the repo (regenerate with scripts/gen_og_card.py when the branding
text changes).
"""
import html
import re


def on_post_page(output, page, config, **kwargs):
    meta = page.meta or {}
    src_uri = getattr(getattr(page, "file", None), "src_uri", "") or ""
    is_english = src_uri.startswith("book-en/") or bool(
        re.fullmatch(r"chapter\d+/README\.en\.md", src_uri)
    )
    site = "AI Agents in Depth" if is_english else config.get("site_name", "")
    title = meta.get("title") or page.title or site
    default_description = (
        "An open-source book on AI agent design principles and engineering "
        "practice, with 10 chapters and 93 companion experiments."
        if is_english
        else config.get("site_description", "")
    )
    desc = meta.get("description") or default_description
    url = page.canonical_url or ""
    locale = "en_US" if is_english else "ko_KR"
    alternate_locale = "ko_KR" if is_english else "en_US"
    image_name = "og-card-en.png" if is_english else "og-card.png"
    image_alt = (
        "AI Agents in Depth — Design Principles and Engineering Practice"
        if is_english
        else "AI 에이전트 깊이 이해하기 — 설계 원리와 엔지니어링 실무"
    )

    if is_english:
        output = output.replace('<html lang="ko"', '<html lang="en"', 1)
        korean_site = html.escape(config.get("site_name", ""))
        output = output.replace(
            f" - {korean_site}</title>",
            f" - {site}</title>",
            1,
        )

    # Static share-card image, generated by scripts/gen_og_card.py and
    # checked in as assets/og-card.png (1200x630). One default card for all
    # pages — crawlers need an absolute URL and a raster format, so the SVG
    # logo won't do.
    image = ""
    site_url = (config.get("site_url") or "").rstrip("/")
    if site_url:
        image = f"{site_url}/assets/{image_name}"

    def add(attr, key, val):
        return f'<meta {attr}="{key}" content="{html.escape(str(val), quote=True)}">'

    tags = []
    if not re.search(r'<meta\s+name=["\']description["\']', output):
        tags.append(add("name", "description", desc))
    tags.extend([
        add("property", "og:type", "website"),
        add("property", "og:site_name", site),
        add("property", "og:title", title),
        add("property", "og:description", desc),
        add("property", "og:url", url),
        add("property", "og:locale", locale),
        add("property", "og:locale:alternate", alternate_locale),
        add("property", "og:image", image),
        add("property", "og:image:width", "1200" if image else ""),
        add("property", "og:image:height", "630" if image else ""),
        add("property", "og:image:alt", image_alt if image else ""),
        add("name", "twitter:card", "summary_large_image" if image else "summary"),
        add("name", "twitter:title", title),
        add("name", "twitter:description", desc),
        add("name", "twitter:image", image),
        add("name", "twitter:image:alt", image_alt if image else ""),
    ])
    block = "\n".join(t for t in tags if 'content=""' not in t)
    return output.replace("</head>", block + "\n</head>", 1)
